load("//test:build_defs.bzl", "scene_diff_test")

scene_diff_test(
    name = "intersection_test",
    golden = "testdata/intersection.png",
    scene = "intersection.muon",
)

scene_diff_test(
    name = "transforms_test",
    golden = "testdata/transforms.png",
    scene = "transforms.muon",
)

scene_diff_test(
    name = "spheres_raytrace_test",
    golden = "testdata/spheres_raytrace.png",
    scene = "spheres_raytrace.muon",
)

scene_diff_test(
    name = "cornell_raytrace_test",
    golden = "testdata/cornell_raytrace.png",
    scene = "cornell_raytrace.muon",
)

scene_diff_test(
    name = "analytic_test",
    golden = "testdata/analytic.png",
    scene = "analytic.muon",
)

scene_diff_test(
    name = "cornell_normals_test",
    golden = "testdata/cornell_normals.png",
    scene = "cornell_normals.muon",
)

scene_diff_test(
    name = "cornell_depth_test",
    golden = "testdata/cornell_depth.png",
    scene = "cornell_depth.muon",
)

scene_diff_test(
    name = "cornell_mesh_test",
    golden = "testdata/cornell_mesh.png",
    scene = "cornell_mesh.muon",
)

scene_diff_test(
    name = "sphere_test",
    golden = "testdata/sphere_golden.png",
    scene = "sphere.muon",
    tolerance = "0.0005",
    truth = "testdata/sphere_truth.png",
)

scene_diff_test(
    name = "cornell_phong_test",
    golden = "testdata/cornell_phong_golden.png",
    scene = "cornell_phong.muon",
    tolerance = "0.002",
    truth = "testdata/cornell_phong_truth.png",
)

scene_diff_test(
    name = "cornell_brdf_test",
    golden = "testdata/cornell_brdf_golden.png",
    scene = "cornell_brdf.muon",
    tolerance = "0.002",
    truth = "testdata/cornell_brdf_truth.png",
)

scene_diff_test(
    name = "ggx_test",
    golden = "testdata/ggx_golden.png",
    scene = "ggx.muon",
    tolerance = "0.002",
    truth = "testdata/ggx_truth.png",
)

scene_diff_test(
    name = "mis_test",
    golden = "testdata/mis_golden.png",
    scene = "mis.muon",
    tolerance = "0.002",
    truth = "testdata/mis_truth.png",
)

scene_diff_test(
    name = "dragon_test",
    golden = "testdata/dragon_golden.png",
    scene = "dragon.muon",
    tolerance = "0.002",
    truth = "testdata/dragon_truth.png",
)

scene_diff_test(
    name = "partial_emission_test",
    golden = "testdata/partial_emission.png",
    scene = "partial_emission.muon",
)

scene_diff_test(
    name = "partial_direct_test",
    golden = "testdata/partial_direct_golden.png",
    scene = "partial_direct.muon",
    tolerance = "0.0005",
    truth = "testdata/partial_direct_truth.png",
)

scene_diff_test(
    name = "partial_indirect_test",
    golden = "testdata/partial_indirect_golden.png",
    scene = "partial_indirect.muon",
    tolerance = "0.001",
    truth = "testdata/partial_indirect_truth.png",
)
